export SHELL := /bin/bash

pdf:
	pdflatex main
	bibtex main
	bibtex main
	pdflatex main
	bibtex main
	pdflatex main
	pdflatex supporting_information
	bibtex supporting_information
	bibtex supporting_information
	pdflatex supporting_information
	bibtex supporting_information
	pdflatex supporting_information
	
main:
	pdflatex main
	bibtex main
	bibtex main
	pdflatex main
	bibtex main
	pdflatex main

supp:
	pdflatex supporting_information
	bibtex supporting_information
	bibtex supporting_information
	pdflatex supporting_information
	bibtex supporting_information
	pdflatex supporting_information
